version: '3'
services:

    laravel.test:
        build:
            context: ./.deploy/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: 'www'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - '.:/var/www/html'
            - './.deploy/8.1/php.ini:/usr/local/etc/php/conf.d/php.ini'
        networks:
            - sail
        depends_on:
            - redis.serv

    redis.serv:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
